name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1.7.0
        with:
          rust-version: stable
      - name: Build
        run: cargo build --release --all-targets
      - name: Run tests
        run: cargo test --all-targets --all-features
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Lint (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings
